FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy script
COPY scraper_imdb.py .

# Run the scraper
CMD ["python", "scraper_imdb.py"]
